language: ruby
rvm:
  - 2.0.0
install: gem install cheatset --no-ri --no-rdoc
before_script:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
script:
  - cd build
  - find ../cheatsheets -name "*.rb" -exec cheatset generate {} \;
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - git checkout ${TRAVIS_BRANCH}
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add build/
  - git commit -m "Build Cheatsheets (build.${TRAVIS_BUILD_NUMBER}.${TRAVIS_COMMIT})"
  - git remote add deploy https://github.com/${TRAVIS_REPO_SLUG}.git
  - git push deploy ${TRAVIS_BRANCH}
env:
  global:
    secure: w7qTqzryxwU96JOja2Hbjybku5vQiOtReVgGaxDM1/IM09M250UyDeOQNXUcAfY/FBotsK2F9W9Gt5oaYuXuOBFQu73ajgM2z5dMjkhv5PoON6h+ijquKMdCzCquY0uzvsDw1xOLntBs3h04NGNXzQQOq3UcU8IKNBuqIXeY3WFBTK5svHqnMJdOAMGQsBg0cVOlRo/qzCHbDUwI8pSR0MEy0ix8Roz58nL8AtqYpTLRUTbaGDtK2GyXwZC7kBZohIGtieEV7KbMP2ifpQtWM1wx0KtFI4YhqifKWE8reIJDr7MuUWe/wRyJq6mfMWma6430esCA8L2C/1h+lestDx90VvOUir6jf0Uh3dvaq+/Jhf474vxqnOmit6dz7PRz+Mfi/Ei+MFLyrgf/Aje8v/16+0xrVQfa8h5RW2LtkKi+qavQfmKKPIJxlIyJ8xbr/sUlpfCZCrY2pjvDR46CpsfZxhRVgFi6hSGkgYKAfBVV5RMUkAEsTEnOTZrLU6m8WbhRIAiOEPtDAzoy4M5o3qWT/5ktPCfV3KvVbRFgueHM1/RyjRfXpXMx7/3Q4sruJPQux1TA3MEX8xJTx1Dt9ixgYWjU4cpNQontzKeEEwiqFiLBdJvoOdWv0N9hEUw1pxCyf8mekw4MZbS2qInwX1orSO2vteDgtI+AJf9TR18=
